{% set name = "marksman" %}
{% set version = "2023-12-09" %}

package:
  name: {{ name|lower }}
  version: "{{ version.replace('-', '_') }}"

source:
  git_url: https://github.com/artempyanykh/marksman
  git_rev: "{{ version }}"

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - marksman --help

about:
  home: https://github.com/artempyanykh/marksman
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Write Markdown with code assist and intelligence in the comfort of your favourite editor
  dev_url: https://github.com/artempyanykh/marksman

extra:
  recipe-maintainers:
    - danielnachun
